---
# Import libraries and data

In [1]:
# base modules
from pathlib import Path
import logging
from collections import OrderedDict

# for manipulating data
import numpy as np
import pandas as pd
import math
from typing import Callable
import copy
import re
from pandas.api.types import is_string_dtype, is_numeric_dtype


# for Machine Learning
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn import metrics
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
from sklearn.model_selection import cross_val_score, KFold, GridSearchCV,train_test_split

# for visualization
from matplotlib import pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# for package auto reload
%load_ext autoreload
%autoreload 2

# for better rendering of plots in jupyter notebook
%matplotlib inline

In [2]:
import optuna

In [3]:
import sys
import os
sys.path.append(os.path.abspath("../src"))
from process_data import log_transform_targets, process_df_keep_nan, clip_outliers

In [4]:
df=pd.read_csv("../data/merged_training_data_clean.csv")

---
# Data Cleaning

In [5]:
df.head()

,Latitude,Longitude,Sample Date,Total Alkalinity,Electrical Conductance,Dissolved Reactive Phosphorus,blue,green,red,nir08,swir16,swir22,NDMI,MNDWI,pet,ppt,tmax,tmin,q
0,-28.760833,17.730278,2011-01-02,128.912,555.0,10.0,9881.0,11481.0,12405.0,11761.5,7791.0,7746.0,0.185538,0.195595,174.2,8.3,35.760000,21.029999,0.4
1,-26.861111,28.884722,2011-01-03,74.720,162.9,163.0,NaN,9550.0,NaN,17658.5,13746.5,10574.0,0.124566,-0.180134,124.1,175.0,25.410000,14.099999,8.8
2,-26.450000,28.085833,2011-01-03,89.254,573.0,80.0,10246.0,10824.0,10213.5,19147.0,15023.5,11040.0,-0.083293,-0.252805,127.5,156.1,26.070000,15.250000,7.8
3,-27.671111,27.236944,2011-01-03,82.000,203.6,101.0,NaN,10943.0,NaN,14887.0,13522.0,11403.0,0.048048,-0.105416,129.7,194.7,27.599998,15.960000,16.1
4,-27.356667,27.286389,2011-01-03,56.100,145.1,151.0,NaN,9502.5,NaN,16828.5,12665.5,9643.0,0.141147,-0.142683,129.2,180.4,27.210000,16.150000,9.0

In [6]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Latitude,9319.0,NaN,NaN,NaN,-28.474988,2.760282,-34.405833,-30.160091,-28.058889,-26.861111,-22.225556
Longitude,9319.0,NaN,NaN,NaN,26.868414,3.535164,17.730278,26.126667,27.40906,29.245556,32.325
Sample Date,9319,1364,2014-01-08,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Alkalinity,9319.0,NaN,NaN,NaN,119.108208,74.692591,4.8,55.811,113.3,170.23,361.676
Electrical Conductance,9319.0,NaN,NaN,NaN,485.004146,341.937736,15.12,207.05,402.0,693.0,1506.0
Dissolved Reactive Phosphorus,9319.0,NaN,NaN,NaN,43.525338,50.980194,5.0,10.0,20.0,48.0,195.0
blue,8178.0,NaN,NaN,NaN,9049.943752,1826.051769,6071.0,8543.0,8924.0,9323.0,54475.5
green,9078.0,NaN,NaN,NaN,10013.609385,1855.255857,4438.5,9429.25,9848.25,10338.25,52339.0
red,8178.0,NaN,NaN,NaN,10336.573245,1938.733531,7179.0,9460.5,10129.0,10951.0,51854.5
nir08,9078.0,NaN,NaN,NaN,14217.92592,2855.227789,4884.0,12826.0,14311.5,15635.625,49593.0
swir16,9078.0,NaN,NaN,NaN,13621.963979,2948.671564,4257.5,11886.625,13769.0,15456.5,37412.0
swir22,9078.0,NaN,NaN,NaN,11455.955111,2310.086186,3878.0,9892.25,11291.5,12883.625,34359.5
NDMI,8234.0,NaN,NaN,NaN,0.021374,0.077897,-0.328293,-0.036869,0.021549,0.073297,0.567905
MNDWI,8234.0,NaN,NaN,NaN,-0.144268,0.097646,-0.300487,-0.21127,-0.167901,-0.104677,0.590974
pet,9319.0,NaN,NaN,NaN,175.166082,29.469867,52.7,156.1,172.5,193.1,270.80002
ppt,9319.0,NaN,NaN,NaN,41.891383,44.910284,0.0,7.3,28.4,59.9,374.5
tmax,9319.0,NaN,NaN,NaN,26.065189,4.3937,12.219999,23.0,26.49,29.289999,38.12
tmin,9319.0,NaN,NaN,NaN,10.383538,5.603319,-3.61,6.24,11.12,14.794999,22.98
q,9319.0,NaN,NaN,NaN,2.808585,9.167971,0.0,0.4,1.4,3.0,266.5

In [7]:
target_cols = ['Total Alkalinity', 'Electrical Conductance', 'Dissolved Reactive Phosphorus']

In [8]:
df['Sample Date'] = pd.to_datetime(df['Sample Date'])
df['year']   = df['Sample Date'].dt.year
df['month']  = df['Sample Date'].dt.month
df['day']    = df['Sample Date'].dt.day
df['doy']    = df['Sample Date'].dt.dayofyear
df['season'] = df['month'] % 12 // 3

In [9]:
df=log_transform_targets(df, target_cols)

In [10]:
for col in ['q', 'ppt', 'tmax', 'tmin']:
    df = clip_outliers(df, col, 0.01, 0.99)

In [12]:
df_pr, y = process_df_keep_nan(
   df,
    y_fields=target_cols,
    skip_flds=['Sample Date']
)

In [13]:
df_pr.shape, y.shape

((9319, 28), (9319, 3))

In [15]:
df_pr.columns

Index(['Latitude', 'Longitude', 'blue', 'green', 'red', 'nir08', 'swir16',
       'swir22', 'NDMI', 'MNDWI', 'pet', 'ppt', 'tmax', 'tmin', 'q', 'year',
       'month', 'day', 'doy', 'season', 'blue_na', 'green_na', 'red_na',
       'nir08_na', 'swir16_na', 'swir22_na', 'NDMI_na', 'MNDWI_na'],
      dtype='object')

--- 
# Model

In [16]:
N_valid = 1000
N_small = 2000
X_train, X_valid, y_train, y_valid = train_test_split(df_pr, y, test_size=N_valid, random_state=42)
_, X_small, _, y_small = train_test_split(X_train, y_train, test_size=N_small, random_state=42)
print("Large training set size : ",X_train.shape, y_train.shape)
print("Small training set size : ",X_small.shape, y_small.shape)
print("Validation set size : ",X_valid.shape, y_valid.shape)

Large training set size :  (8319, 28) (8319, 3)
Small training set size :  (2000, 28) (2000, 3)
Validation set size :  (1000, 28) (1000, 3)

In [17]:
def rmse(y_gold, y_pred):
    """
    y_gold, y_pred: 可以是一维或二维（多输出）
    返回：整体 RMSE（对所有样本 & 所有 target 统一算一个）
    """
    y_gold = np.asarray(y_gold)
    y_pred = np.asarray(y_pred)
    return float(np.sqrt(np.mean((y_gold - y_pred) ** 2)))

In [18]:
def print_score(m, X_train, y_train, X_valid, y_valid, log_target=True):
    y_train_pred_log = m.predict(X_train)
    y_valid_pred_log = m.predict(X_valid)
    print('1. RMSE on train set (log_y): {:.4f}'.format(rmse(y_train, y_train_pred_log)))
    print('2. RMSE on valid set (log_y): {:.4f}'.format(rmse(y_valid, y_valid_pred_log)))
    print('3. MAE on train set (log_y): {:.4f}'.format(mean_absolute_error(y_train, y_train_pred_log)))
    print('4. MAE on valid set (log_y): {:.4f}'.format(mean_absolute_error(y_valid, y_valid_pred_log)))
    if log_target:
        y_train_real      = np.expm1(y_train)
        y_valid_real      = np.expm1(y_valid)
        y_train_pred_real = np.expm1(y_train_pred_log)
        y_valid_pred_real = np.expm1(y_valid_pred_log)
        print('5. R^2 on train set (original y): {:.4f}'.format(
            r2_score(y_train_real, y_train_pred_real)))
        print('6. R^2 on valid set (original y): {:.4f}'.format(
            r2_score(y_valid_real, y_valid_pred_real)))

    else:
        print('5. R^2 on train set: {:.4f}'.format(m.score(X_train, y_train)))
        print('6. R^2 on valid set: {:.4f}'.format(m.score(X_valid, y_valid)))
    if hasattr(m, 'oob_score_'):
        print('R^2 on oob set: {:.4f}'.format(m.oob_score_))

    return

--- 
# Random Forest

In [19]:
def objective(trial, X_training, y_training, X_validation, y_validation):
    n_estimators = trial.suggest_int('n_estimators', 100, 2500) 
    max_depth = trial.suggest_int('max_depth', 5, 60, log=True) 
    min_samples_split = trial.suggest_int('min_samples_split', 2, 50, log=True) 
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 30, log=True) 
    max_features = trial.suggest_float('max_features', 0.1, 1.0)
    bootstrap = trial.suggest_categorical('bootstrap', [True, False])
    max_samples = trial.suggest_float('max_samples', 0.5, 1.0, step=0.05) if bootstrap else None
    
    rf = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        bootstrap=bootstrap,
        max_samples=max_samples, 
        random_state=42,
        n_jobs=-1,
    )
    rf.fit(X_training, y_training)

    y_pred_validation = rf.predict(X_validation)
    r2_validation = metrics.r2_score(y_validation, y_pred_validation)

    return r2_validation

In [20]:
study = optuna.create_study(
    study_name="rf_study2", 
    load_if_exists=True, 
    storage="sqlite:///opt.db",
    direction="maximize"
)
study.optimize(
    lambda trial: objective(trial, X_small, y_small, X_valid, y_valid),
    n_trials=50,
    show_progress_bar=True
)

[I 2026-03-03 10:50:38,813] A new study created in RDB with name: rf_study2

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-03-03 10:50:41,620] Trial 0 finished with value: 0.7398718799462145 and parameters: {'n_estimators': 1559, 'max_depth': 45, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 0.532900090296172, 'bootstrap': False}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:42,144] Trial 1 finished with value: 0.5758201235219644 and parameters: {'n_estimators': 634, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 2, 'max_features': 0.2090641769247762, 'bootstrap': False}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:44,022] Trial 2 finished with value: 0.4899979274335054 and parameters: {'n_estimators': 2458, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 13, 'max_features': 0.4970017277865053, 'bootstrap': False}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:45,456] Trial 3 finished with value: 0.6513378941317579 and parameters: {'n_estimators': 1262, 'max_depth': 38, 'min_samples_split': 33, 'min_samples_leaf': 3, 'max_features': 0.8784415041211237, 'bootstrap': True, 'max_samples': 0.8}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:45,882] Trial 4 finished with value: 0.5900188354091398 and parameters: {'n_estimators': 370, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2, 'max_features': 0.5770940550941918, 'bootstrap': False}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:46,211] Trial 5 finished with value: 0.47216240351320304 and parameters: {'n_estimators': 422, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 24, 'max_features': 0.22681568951917772, 'bootstrap': False}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:46,883] Trial 6 finished with value: 0.44498692700630943 and parameters: {'n_estimators': 771, 'max_depth': 17, 'min_samples_split': 22, 'min_samples_leaf': 19, 'max_features': 0.2414812963134355, 'bootstrap': True, 'max_samples': 0.95}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:48,621] Trial 7 finished with value: 0.528826688541756 and parameters: {'n_estimators': 2122, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.8506969762040465, 'bootstrap': True, 'max_samples': 0.5}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:49,122] Trial 8 finished with value: 0.41341470201104347 and parameters: {'n_estimators': 600, 'max_depth': 60, 'min_samples_split': 29, 'min_samples_leaf': 18, 'max_features': 0.2213653404980514, 'bootstrap': True, 'max_samples': 0.55}. Best is trial 0 with value: 0.7398718799462145.
[I 2026-03-03 10:50:51,118] Trial 9 finished with value: 0.740183620760181 and parameters: {'n_estimators': 1291, 'max_depth': 31, 'min_samples_split': 11, 'min_samples_leaf': 2, 'max_features': 0.551811161566505, 'bootstrap': False}. Best is trial 9 with value: 0.740183620760181.
[I 2026-03-03 10:50:53,601] Trial 10 finished with value: 0.7435497968683205 and parameters: {'n_estimators': 1427, 'max_depth': 25, 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_features': 0.7337799771055458, 'bootstrap': False}. Best is trial 10 with value: 0.7435497968683205.
[I 2026-03-03 10:50:55,570] Trial 11 finished with value: 0.7335225935618411 and parameters: {'n_estimators': 1259, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 7, 'max_features': 0.7101585154395079, 'bootstrap': False}. Best is trial 10 with value: 0.7435497968683205.
[I 2026-03-03 10:50:58,610] Trial 12 finished with value: 0.7487598416995244 and parameters: {'n_estimators': 1788, 'max_depth': 26, 'min_samples_split': 17, 'min_samples_leaf': 1, 'max_features': 0.7164022259476804, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:02,646] Trial 13 finished with value: 0.6882956765010744 and parameters: {'n_estimators': 1745, 'max_depth': 21, 'min_samples_split': 17, 'min_samples_leaf': 1, 'max_features': 0.9869292163284018, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:05,500] Trial 14 finished with value: 0.7266731499215416 and parameters: {'n_estimators': 1870, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 7, 'max_features': 0.7196486306719012, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:06,441] Trial 15 finished with value: 0.617503035340422 and parameters: {'n_estimators': 976, 'max_depth': 26, 'min_samples_split': 49, 'min_samples_leaf': 5, 'max_features': 0.3966983742946149, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:09,759] Trial 16 finished with value: 0.7294596647004911 and parameters: {'n_estimators': 2146, 'max_depth': 19, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 0.7032707947771626, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:13,118] Trial 17 finished with value: 0.7467512125460699 and parameters: {'n_estimators': 1584, 'max_depth': 36, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 0.8563349781673519, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:16,543] Trial 18 finished with value: 0.7441252660792385 and parameters: {'n_estimators': 1835, 'max_depth': 50, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 0.9866609514346711, 'bootstrap': True, 'max_samples': 1.0}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:21,509] Trial 19 finished with value: 0.7469741178785219 and parameters: {'n_estimators': 2237, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 0.8320321309340135, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:25,680] Trial 20 finished with value: 0.7425349117830565 and parameters: {'n_estimators': 2449, 'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 3, 'max_features': 0.7925000952061649, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:31,298] Trial 21 finished with value: 0.7252607279834428 and parameters: {'n_estimators': 2130, 'max_depth': 35, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 0.8937656217641593, 'bootstrap': False}. Best is trial 12 with value: 0.7487598416995244.
[I 2026-03-03 10:51:34,770] Trial 22 finished with value: 0.7558729344601778 and parameters: {'n_estimators': 1650, 'max_depth': 33, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.6440222440923906, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:38,486] Trial 23 finished with value: 0.7551227604091247 and parameters: {'n_estimators': 1941, 'max_depth': 29, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.6357115681379603, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:42,181] Trial 24 finished with value: 0.7551230831750111 and parameters: {'n_estimators': 1902, 'max_depth': 44, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.6347670127109767, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:45,942] Trial 25 finished with value: 0.7551455262403142 and parameters: {'n_estimators': 1967, 'max_depth': 50, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.6325672229074594, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:47,280] Trial 26 finished with value: 0.6321266508354659 and parameters: {'n_estimators': 1583, 'max_depth': 47, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.4142101885642727, 'bootstrap': True, 'max_samples': 0.7}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:49,200] Trial 27 finished with value: 0.7548744206037302 and parameters: {'n_estimators': 1024, 'max_depth': 54, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.6231049748710605, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:51,726] Trial 28 finished with value: 0.7103194905469857 and parameters: {'n_estimators': 2029, 'max_depth': 42, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.44445635067295547, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:53,150] Trial 29 finished with value: 0.6109495806451027 and parameters: {'n_estimators': 1635, 'max_depth': 44, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': 0.32630371155606364, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:56,312] Trial 30 finished with value: 0.7286561543368592 and parameters: {'n_estimators': 2271, 'max_depth': 55, 'min_samples_split': 2, 'min_samples_leaf': 3, 'max_features': 0.49917415514361574, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:51:59,768] Trial 31 finished with value: 0.7551260564717953 and parameters: {'n_estimators': 1900, 'max_depth': 42, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.6281021517119993, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:02,272] Trial 32 finished with value: 0.7549369382086596 and parameters: {'n_estimators': 1427, 'max_depth': 41, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.6367804880801807, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:05,670] Trial 33 finished with value: 0.751430973984036 and parameters: {'n_estimators': 1986, 'max_depth': 34, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.6231368813971535, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:05,991] Trial 34 finished with value: 0.7405158458460285 and parameters: {'n_estimators': 138, 'max_depth': 48, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.5500794709093494, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:09,399] Trial 35 finished with value: 0.7550190116867664 and parameters: {'n_estimators': 1709, 'max_depth': 60, 'min_samples_split': 9, 'min_samples_leaf': 4, 'max_features': 0.7718440197247185, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:11,839] Trial 36 finished with value: 0.7470597040855248 and parameters: {'n_estimators': 1462, 'max_depth': 39, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 0.6631741797925155, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:13,763] Trial 37 finished with value: 0.4016916610335041 and parameters: {'n_estimators': 2375, 'max_depth': 21, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.10247246453727954, 'bootstrap': True, 'max_samples': 0.75}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:17,238] Trial 38 finished with value: 0.7511182958774251 and parameters: {'n_estimators': 1913, 'max_depth': 45, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 0.5777277294760748, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:19,781] Trial 39 finished with value: 0.712991044018982 and parameters: {'n_estimators': 2043, 'max_depth': 13, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 0.498039934886785, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:22,544] Trial 40 finished with value: 0.6985337212234978 and parameters: {'n_estimators': 2273, 'max_depth': 32, 'min_samples_split': 4, 'min_samples_leaf': 3, 'max_features': 0.7757950660747754, 'bootstrap': True, 'max_samples': 0.65}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:25,796] Trial 41 finished with value: 0.7514726557192665 and parameters: {'n_estimators': 1910, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 0.60066959386113, 'bootstrap': False}. Best is trial 22 with value: 0.7558729344601778.
[I 2026-03-03 10:52:29,285] Trial 42 finished with value: 0.7560786829638765 and parameters: {'n_estimators': 1751, 'max_depth': 38, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 0.658035356275404, 'bootstrap': False}. Best is trial 42 with value: 0.7560786829638765.
[I 2026-03-03 10:52:32,668] Trial 43 finished with value: 0.7559790903712104 and parameters: {'n_estimators': 1683, 'max_depth': 37, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.6786838110268555, 'bootstrap': False}. Best is trial 42 with value: 0.7560786829638765.
[I 2026-03-03 10:52:37,764] Trial 44 finished with value: 0.7541534046874139 and parameters: {'n_estimators': 1710, 'max_depth': 38, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 0.6833055678413067, 'bootstrap': False}. Best is trial 42 with value: 0.7560786829638765.
[I 2026-03-03 10:52:41,477] Trial 45 finished with value: 0.7303548560718073 and parameters: {'n_estimators': 1517, 'max_depth': 53, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 0.5295058271827399, 'bootstrap': False}. Best is trial 42 with value: 0.7560786829638765.
[I 2026-03-03 10:52:44,307] Trial 46 finished with value: 0.5980429651651319 and parameters: {'n_estimators': 1334, 'max_depth': 23, 'min_samples_split': 6, 'min_samples_leaf': 27, 'max_features': 0.7509488178742918, 'bootstrap': False}. Best is trial 42 with value: 0.7560786829638765.
[I 2026-03-03 10:52:47,875] Trial 47 finished with value: 0.7542339706454375 and parameters: {'n_estimators': 1197, 'max_depth': 16, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 0.674058759002656, 'bootstrap': False}. Best is trial 42 with value: 0.7560786829638765.
[I 2026-03-03 10:52:50,403] Trial 48 finished with value: 0.6689945192810831 and parameters: {'n_estimators': 1664, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 0.5782842604949902, 'bootstrap': True, 'max_samples': 0.8500000000000001}. Best is trial 42 with value: 0.7560786829638765.
[I 2026-03-03 10:52:55,038] Trial 49 finished with value: 0.6993465631765066 and parameters: {'n_estimators': 1818, 'max_depth': 34, 'min_samples_split': 9, 'min_samples_leaf': 13, 'max_features': 0.8158158285854662, 'bootstrap': False}. Best is trial 42 with value: 0.7560786829638765.

In [21]:
study.best_params

{'n_estimators': 1751,
 'max_depth': 38,
 'min_samples_split': 4,
 'min_samples_leaf': 2,
 'max_features': 0.658035356275404,
 'bootstrap': False}

In [22]:
rf_best = RandomForestRegressor(
        n_estimators=1751,
        max_depth=38,
        min_samples_split=4,
        min_samples_leaf=2,
        max_features=0.658035356275404,
        bootstrap=False,
        random_state=42,
        n_jobs=-1,
    )
%time rf_best.fit(X_train, y_train)
print_score(rf_best, X_train, y_train, X_valid, y_valid)

CPU times: total: 2min 34s
Wall time: 11.8 s
1. RMSE on train set (log_y): 0.1058
2. RMSE on valid set (log_y): 0.3649
3. MAE on train set (log_y): 0.0606
4. MAE on valid set (log_y): 0.2237
5. R^2 on train set (original y): 0.9762
6. R^2 on valid set (original y): 0.8145

In [23]:
import joblib

joblib.dump(rf_best, '../user_data/rf_best.joblib')

['../user_data/rf_best.joblib']

---
# XGBoost

In [24]:
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from catboost import CatBoostRegressor, Pool, cv, CatBoostClassifier
from sklearn.model_selection import cross_val_score, KFold, GridSearchCV, train_test_split
from sklearn import metrics
from xgboost import XGBRegressor, plot_tree
import seaborn as sns

In [25]:
def reg_perf(regressor, X_training, X_validation, y_true_training, y_true_validation):
    y_pred_training = regressor.predict(X_training)
    y_pred_validation = regressor.predict(X_validation)
    rmse_training = metrics.root_mean_squared_error(y_true_training, y_pred_training)
    rmse_validation = metrics.root_mean_squared_error(y_true_validation, y_pred_validation)
    r2_training = metrics.r2_score(y_true_training, y_pred_training)
    r2_validation = metrics.r2_score(y_true_validation, y_pred_validation)
    print("RMSE on training set : {:.3f}".format(rmse_training))
    print("RMSE on validation set : {:.3f}".format(rmse_validation))
    print("R^2 on training set : {:.3f}".format(r2_training))
    print("R^2 on validation set : {:.3f}".format(r2_validation))

In [26]:
def objective(trial, X_training, y_training, X_validation, y_validation):
    
    learning_rate_guess = trial.suggest_float("learning_rate", 1e-3, 1, log=True)
    max_depth_guess = trial.suggest_int("max_depth", 2, 30, log=False)
    reg_lambda_guess = trial.suggest_int("reg_lambda", 1,100, log=False)
    colsample_bytree_guess = trial.suggest_float("colsample_bytree", 0.3, 1.0, log=False)
    min_child_weight_guess = trial.suggest_int("min_child_weight", 1, 10, log=False)
    subsample_guess = trial.suggest_float("subsample", 0.5, 1.0, log=False)
    gamma_guess = trial.suggest_float("gamma", 0.0, 5.0, log=False)
    reg_alpha_guess = trial.suggest_float("reg_alpha", 1e-8, 100.0, log=True)

    
    xgb = XGBRegressor(
        n_estimators=1000,                              
        random_state=42,
        learning_rate=learning_rate_guess,       
        max_depth=max_depth_guess, 
        reg_lambda=reg_lambda_guess,
        verbosity=0,
        colsample_bytree=colsample_bytree_guess,
        min_child_weight=min_child_weight_guess,   
        subsample=subsample_guess  ,
        gamma=gamma_guess,      
        reg_alpha=reg_alpha_guess  
    )
    
    xgb.fit(X_training, y_training)
    
    y_pred_validation = xgb.predict(X_validation)
    r2_validation = metrics.r2_score(y_validation, y_pred_validation)
    return r2_validation

In [27]:
study = optuna.create_study(study_name="xgb_study2", 
                            load_if_exists=True, 
                            storage = "sqlite:///opt.db",
                            direction="maximize")

study.optimize(lambda trial: objective(trial, X_small, y_small, X_valid, y_valid), n_trials=50, show_progress_bar=True)

[I 2026-03-03 10:54:07,690] A new study created in RDB with name: xgb_study2

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-03-03 10:54:10,711] Trial 0 finished with value: 0.7034945973458772 and parameters: {'learning_rate': 0.1068831825935791, 'max_depth': 11, 'reg_lambda': 15, 'colsample_bytree': 0.7074345386101175, 'min_child_weight': 4, 'subsample': 0.9137509426967863, 'gamma': 0.7964549120981745, 'reg_alpha': 9.098022120788824e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:11,365] Trial 1 finished with value: 0.6469519357807345 and parameters: {'learning_rate': 0.057311557033451185, 'max_depth': 24, 'reg_lambda': 38, 'colsample_bytree': 0.596319784546688, 'min_child_weight': 8, 'subsample': 0.5193759819921581, 'gamma': 1.0641643423362024, 'reg_alpha': 7.529497617260533e-05}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:11,834] Trial 2 finished with value: 0.6685444992616735 and parameters: {'learning_rate': 0.48235698395665755, 'max_depth': 27, 'reg_lambda': 19, 'colsample_bytree': 0.32549409567726245, 'min_child_weight': 5, 'subsample': 0.8247739763383405, 'gamma': 0.3302861022779502, 'reg_alpha': 1.9911994184340047e-05}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:13,102] Trial 3 finished with value: 0.5928872337614837 and parameters: {'learning_rate': 0.0038583943645364234, 'max_depth': 23, 'reg_lambda': 16, 'colsample_bytree': 0.8839339579626244, 'min_child_weight': 3, 'subsample': 0.7375027430887362, 'gamma': 3.5695517674325403, 'reg_alpha': 2.3653765250582857e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:13,566] Trial 4 finished with value: 0.6152243298484609 and parameters: {'learning_rate': 0.2799100776591745, 'max_depth': 6, 'reg_lambda': 76, 'colsample_bytree': 0.5690318523306652, 'min_child_weight': 4, 'subsample': 0.5784363082031447, 'gamma': 1.151598398957664, 'reg_alpha': 1.8588799090931074}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:14,568] Trial 5 finished with value: 0.5233126153223114 and parameters: {'learning_rate': 0.0029586835575092702, 'max_depth': 4, 'reg_lambda': 22, 'colsample_bytree': 0.5695394661071614, 'min_child_weight': 2, 'subsample': 0.6902854043745345, 'gamma': 3.109539675888879, 'reg_alpha': 0.0006072202790167684}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:15,625] Trial 6 finished with value: 0.5705932968629633 and parameters: {'learning_rate': 0.004814321832787238, 'max_depth': 18, 'reg_lambda': 21, 'colsample_bytree': 0.6165814172258669, 'min_child_weight': 9, 'subsample': 0.8371750658125905, 'gamma': 4.202734932168072, 'reg_alpha': 0.252376865165617}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:16,026] Trial 7 finished with value: 0.402880218720513 and parameters: {'learning_rate': 0.7739918210465206, 'max_depth': 25, 'reg_lambda': 49, 'colsample_bytree': 0.9015578902927626, 'min_child_weight': 5, 'subsample': 0.6105430444734463, 'gamma': 4.990346271343765, 'reg_alpha': 19.757865856257162}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:18,632] Trial 8 finished with value: 0.6217353357748817 and parameters: {'learning_rate': 0.006522939294152755, 'max_depth': 29, 'reg_lambda': 87, 'colsample_bytree': 0.9324256933781718, 'min_child_weight': 2, 'subsample': 0.6098770137671826, 'gamma': 0.3716559218781801, 'reg_alpha': 0.0035016403295954858}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:19,993] Trial 9 finished with value: 0.6109391911874279 and parameters: {'learning_rate': 0.03653988678474799, 'max_depth': 9, 'reg_lambda': 46, 'colsample_bytree': 0.9397403086143026, 'min_child_weight': 6, 'subsample': 0.5395124291311246, 'gamma': 0.1371178319587668, 'reg_alpha': 10.578967774371732}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:20,457] Trial 10 finished with value: 0.6845700559961969 and parameters: {'learning_rate': 0.14666357161212135, 'max_depth': 14, 'reg_lambda': 1, 'colsample_bytree': 0.7733819604000594, 'min_child_weight': 7, 'subsample': 0.99456925773735, 'gamma': 2.1589424844671425, 'reg_alpha': 1.749482978944557e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:20,909] Trial 11 finished with value: 0.6883441307366779 and parameters: {'learning_rate': 0.12382545559091238, 'max_depth': 12, 'reg_lambda': 2, 'colsample_bytree': 0.7576363734449671, 'min_child_weight': 7, 'subsample': 0.993250777422604, 'gamma': 1.9956990435174897, 'reg_alpha': 3.256943748577727e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:21,371] Trial 12 finished with value: 0.6883664738550662 and parameters: {'learning_rate': 0.11272792831309497, 'max_depth': 11, 'reg_lambda': 2, 'colsample_bytree': 0.7719665066611259, 'min_child_weight': 7, 'subsample': 0.9850677798498594, 'gamma': 2.079016621796754, 'reg_alpha': 1.622272201183912e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:22,133] Trial 13 finished with value: 0.6188290937630427 and parameters: {'learning_rate': 0.018900401043380487, 'max_depth': 16, 'reg_lambda': 68, 'colsample_bytree': 0.7091508720383282, 'min_child_weight': 10, 'subsample': 0.8884508315809608, 'gamma': 1.5055990828399186, 'reg_alpha': 2.595151944359329e-06}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:22,571] Trial 14 finished with value: 0.5982649753022048 and parameters: {'learning_rate': 0.08161220278840568, 'max_depth': 9, 'reg_lambda': 34, 'colsample_bytree': 0.3771518041765891, 'min_child_weight': 4, 'subsample': 0.9077697415527199, 'gamma': 2.6582083320373653, 'reg_alpha': 1.1171491065348649e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:23,548] Trial 15 finished with value: 0.6969053591480453 and parameters: {'learning_rate': 0.011556461089486655, 'max_depth': 19, 'reg_lambda': 7, 'colsample_bytree': 0.8166439415484044, 'min_child_weight': 1, 'subsample': 0.9321642605134881, 'gamma': 1.6006855877854744, 'reg_alpha': 9.521498923237075e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:24,556] Trial 16 finished with value: 0.6392255144230135 and parameters: {'learning_rate': 0.013941409179167917, 'max_depth': 19, 'reg_lambda': 62, 'colsample_bytree': 0.45009437984741774, 'min_child_weight': 1, 'subsample': 0.8957513905208948, 'gamma': 1.0188182942090704, 'reg_alpha': 2.24862159686098e-06}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:26,830] Trial 17 finished with value: 0.4295555707805083 and parameters: {'learning_rate': 0.0010606060455580538, 'max_depth': 20, 'reg_lambda': 31, 'colsample_bytree': 0.6800765935743868, 'min_child_weight': 1, 'subsample': 0.8190472916377217, 'gamma': 1.5533941481042755, 'reg_alpha': 0.0012162956469486657}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:27,482] Trial 18 finished with value: 0.5663492050492108 and parameters: {'learning_rate': 0.011943815498952282, 'max_depth': 2, 'reg_lambda': 12, 'colsample_bytree': 0.827662253018894, 'min_child_weight': 3, 'subsample': 0.735929972524201, 'gamma': 0.7501366350259552, 'reg_alpha': 0.020766688183746912}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:27,992] Trial 19 finished with value: 0.6040713604194002 and parameters: {'learning_rate': 0.033811976954048494, 'max_depth': 16, 'reg_lambda': 31, 'colsample_bytree': 0.4719001284954327, 'min_child_weight': 3, 'subsample': 0.9548884752820473, 'gamma': 2.736509920271863, 'reg_alpha': 1.1888287054644188e-05}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:31,036] Trial 20 finished with value: 0.6397849140128806 and parameters: {'learning_rate': 0.0016701316812974055, 'max_depth': 21, 'reg_lambda': 9, 'colsample_bytree': 0.9934996574219341, 'min_child_weight': 1, 'subsample': 0.9391401765082389, 'gamma': 1.6443176901390288, 'reg_alpha': 6.760447669095417e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:31,463] Trial 21 finished with value: 0.6678746404226884 and parameters: {'learning_rate': 0.2097747338669203, 'max_depth': 10, 'reg_lambda': 7, 'colsample_bytree': 0.8104988778218368, 'min_child_weight': 6, 'subsample': 0.8694595754774581, 'gamma': 2.1950450029654296, 'reg_alpha': 6.133749278515715e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:31,968] Trial 22 finished with value: 0.6512777636026742 and parameters: {'learning_rate': 0.06120837205433652, 'max_depth': 13, 'reg_lambda': 26, 'colsample_bytree': 0.7240154760081726, 'min_child_weight': 7, 'subsample': 0.9622386269084533, 'gamma': 1.8963816036121306, 'reg_alpha': 9.122218822513074e-05}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:32,410] Trial 23 finished with value: 0.6846614127371856 and parameters: {'learning_rate': 0.4296953657985775, 'max_depth': 11, 'reg_lambda': 1, 'colsample_bytree': 0.8412112090989051, 'min_child_weight': 8, 'subsample': 0.9312076220357577, 'gamma': 0.6965507170851435, 'reg_alpha': 1.3731083405049972e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:32,967] Trial 24 finished with value: 0.6223961865838997 and parameters: {'learning_rate': 0.02393495949266298, 'max_depth': 7, 'reg_lambda': 13, 'colsample_bytree': 0.6730039766736474, 'min_child_weight': 4, 'subsample': 0.7976943064609974, 'gamma': 3.1807906572546925, 'reg_alpha': 9.421061391096917e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:33,469] Trial 25 finished with value: 0.6584245066779276 and parameters: {'learning_rate': 0.10138899088838015, 'max_depth': 15, 'reg_lambda': 40, 'colsample_bytree': 0.765424900791133, 'min_child_weight': 2, 'subsample': 0.859196165807824, 'gamma': 1.3211343712688288, 'reg_alpha': 1.3883520257974064e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:34,511] Trial 26 finished with value: 0.665206470245201 and parameters: {'learning_rate': 0.008032327370532024, 'max_depth': 18, 'reg_lambda': 11, 'colsample_bytree': 0.8486948256333621, 'min_child_weight': 5, 'subsample': 0.9770975290321131, 'gamma': 2.421497448251421, 'reg_alpha': 1.0649391263101168e-05}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:35,015] Trial 27 finished with value: 0.6809460509197969 and parameters: {'learning_rate': 0.2457498365890044, 'max_depth': 7, 'reg_lambda': 56, 'colsample_bytree': 0.6348529682773657, 'min_child_weight': 8, 'subsample': 0.780004040067892, 'gamma': 0.5365987780364714, 'reg_alpha': 5.313052698019106e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:35,569] Trial 28 finished with value: 0.6430314430970427 and parameters: {'learning_rate': 0.03542550516491901, 'max_depth': 13, 'reg_lambda': 28, 'colsample_bytree': 0.5269489142437644, 'min_child_weight': 6, 'subsample': 0.920091484480932, 'gamma': 1.8073660589850926, 'reg_alpha': 0.0001117502054111076}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:36,152] Trial 29 finished with value: 0.672256190441586 and parameters: {'learning_rate': 0.051717045192132965, 'max_depth': 24, 'reg_lambda': 40, 'colsample_bytree': 0.7253387235383721, 'min_child_weight': 7, 'subsample': 0.9997796008247418, 'gamma': 0.8908896865318716, 'reg_alpha': 7.607098742964519e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:36,645] Trial 30 finished with value: 0.6557362920461985 and parameters: {'learning_rate': 0.06191887022347848, 'max_depth': 17, 'reg_lambda': 6, 'colsample_bytree': 0.7977670393523146, 'min_child_weight': 9, 'subsample': 0.6883497119905228, 'gamma': 2.41160161341539, 'reg_alpha': 3.3249344118880485e-06}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:37,102] Trial 31 finished with value: 0.6916401495889234 and parameters: {'learning_rate': 0.1389809291824302, 'max_depth': 12, 'reg_lambda': 2, 'colsample_bytree': 0.7526238173024853, 'min_child_weight': 7, 'subsample': 0.9601563630455188, 'gamma': 2.0431473470165127, 'reg_alpha': 3.88224221847506e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:37,530] Trial 32 finished with value: 0.6600861511512388 and parameters: {'learning_rate': 0.3728801794378526, 'max_depth': 11, 'reg_lambda': 17, 'colsample_bytree': 0.671148293613126, 'min_child_weight': 9, 'subsample': 0.9446413520442135, 'gamma': 1.137810611302443, 'reg_alpha': 3.076103399052577e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:37,989] Trial 33 finished with value: 0.69036872478631 and parameters: {'learning_rate': 0.15768771201791382, 'max_depth': 9, 'reg_lambda': 7, 'colsample_bytree': 0.739935301690905, 'min_child_weight': 6, 'subsample': 0.8674476319591926, 'gamma': 1.3683314309529955, 'reg_alpha': 1.0541694092143881e-08}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:38,434] Trial 34 finished with value: 0.6668687942223631 and parameters: {'learning_rate': 0.1789512468412182, 'max_depth': 5, 'reg_lambda': 20, 'colsample_bytree': 0.8727139424488563, 'min_child_weight': 6, 'subsample': 0.8596564728940292, 'gamma': 1.3488404689274558, 'reg_alpha': 2.4691760828410644e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:38,861] Trial 35 finished with value: 0.6284351171207295 and parameters: {'learning_rate': 0.7292966632093398, 'max_depth': 22, 'reg_lambda': 100, 'colsample_bytree': 0.7195974274782452, 'min_child_weight': 4, 'subsample': 0.8864433325997747, 'gamma': 1.2426628213334099, 'reg_alpha': 7.300246801130075e-06}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:39,283] Trial 36 finished with value: 0.6368416180647735 and parameters: {'learning_rate': 0.3204689524741891, 'max_depth': 9, 'reg_lambda': 16, 'colsample_bytree': 0.5945444368417558, 'min_child_weight': 5, 'subsample': 0.9132524395309133, 'gamma': 2.9616094354307574, 'reg_alpha': 4.936646188080945e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:39,776] Trial 37 finished with value: 0.6550718030451385 and parameters: {'learning_rate': 0.08063953258138383, 'max_depth': 14, 'reg_lambda': 23, 'colsample_bytree': 0.6423688401993561, 'min_child_weight': 3, 'subsample': 0.8309754610148026, 'gamma': 1.6792173586544927, 'reg_alpha': 2.7809282353407356e-05}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:40,265] Trial 38 finished with value: 0.678114844277062 and parameters: {'learning_rate': 0.5211088663005541, 'max_depth': 7, 'reg_lambda': 9, 'colsample_bytree': 0.540808294961754, 'min_child_weight': 5, 'subsample': 0.7605989731538716, 'gamma': 0.12648873320048792, 'reg_alpha': 1.3560816565685147e-07}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:40,671] Trial 39 finished with value: 0.49475857575619037 and parameters: {'learning_rate': 0.1697555450082409, 'max_depth': 2, 'reg_lambda': 16, 'colsample_bytree': 0.6977868735093564, 'min_child_weight': 8, 'subsample': 0.9613419186123895, 'gamma': 3.7068443025051536, 'reg_alpha': 0.00021142177718640122}. Best is trial 0 with value: 0.7034945973458772.
[I 2026-03-03 10:54:41,477] Trial 40 finished with value: 0.729080937562137 and parameters: {'learning_rate': 0.04764735877571296, 'max_depth': 27, 'reg_lambda': 5, 'colsample_bytree': 0.903962730133244, 'min_child_weight': 2, 'subsample': 0.7047038015011124, 'gamma': 0.4903310039013243, 'reg_alpha': 2.8546708698307437e-05}. Best is trial 40 with value: 0.729080937562137.
[I 2026-03-03 10:54:42,324] Trial 41 finished with value: 0.7249974036416907 and parameters: {'learning_rate': 0.04742096512359319, 'max_depth': 28, 'reg_lambda': 7, 'colsample_bytree': 0.8961507650557274, 'min_child_weight': 2, 'subsample': 0.6820462887958314, 'gamma': 0.4298926809592774, 'reg_alpha': 2.807567040773751e-05}. Best is trial 40 with value: 0.729080937562137.
[I 2026-03-03 10:54:43,540] Trial 42 finished with value: 0.730297340338305 and parameters: {'learning_rate': 0.02212488542871817, 'max_depth': 30, 'reg_lambda': 5, 'colsample_bytree': 0.915830103274166, 'min_child_weight': 2, 'subsample': 0.6994086343520101, 'gamma': 0.40877113364972884, 'reg_alpha': 0.00037891042863194194}. Best is trial 42 with value: 0.730297340338305.
[I 2026-03-03 10:54:45,074] Trial 43 finished with value: 0.7208631308044925 and parameters: {'learning_rate': 0.019943951158474887, 'max_depth': 29, 'reg_lambda': 14, 'colsample_bytree': 0.9202230828735473, 'min_child_weight': 2, 'subsample': 0.6681620589280536, 'gamma': 0.35186510497862944, 'reg_alpha': 0.01417351714203642}. Best is trial 42 with value: 0.730297340338305.
[I 2026-03-03 10:54:46,551] Trial 44 finished with value: 0.7076627246301769 and parameters: {'learning_rate': 0.022062548004291523, 'max_depth': 30, 'reg_lambda': 25, 'colsample_bytree': 0.9824170830144262, 'min_child_weight': 2, 'subsample': 0.6630710066370439, 'gamma': 0.428825429114599, 'reg_alpha': 0.019028932989530616}. Best is trial 42 with value: 0.730297340338305.
[I 2026-03-03 10:54:48,159] Trial 45 finished with value: 0.7122402543574798 and parameters: {'learning_rate': 0.022427577030276886, 'max_depth': 30, 'reg_lambda': 25, 'colsample_bytree': 0.9618305112124934, 'min_child_weight': 2, 'subsample': 0.6748025332113595, 'gamma': 0.3577579412278928, 'reg_alpha': 0.05628260768705672}. Best is trial 42 with value: 0.730297340338305.
[I 2026-03-03 10:54:50,136] Trial 46 finished with value: 0.72628832722918 and parameters: {'learning_rate': 0.04535934201430916, 'max_depth': 28, 'reg_lambda': 21, 'colsample_bytree': 0.9294895068394281, 'min_child_weight': 2, 'subsample': 0.6456522914953898, 'gamma': 0.09685238312285782, 'reg_alpha': 0.1705146945081231}. Best is trial 42 with value: 0.730297340338305.
[I 2026-03-03 10:54:54,733] Trial 47 finished with value: 0.7176199586382487 and parameters: {'learning_rate': 0.04235937018330603, 'max_depth': 27, 'reg_lambda': 20, 'colsample_bytree': 0.9248326343511932, 'min_child_weight': 2, 'subsample': 0.6405787802714672, 'gamma': 0.005670063960276625, 'reg_alpha': 1.0383871921301893}. Best is trial 42 with value: 0.730297340338305.
[I 2026-03-03 10:54:56,134] Trial 48 finished with value: 0.7056032862182761 and parameters: {'learning_rate': 0.015506093036642233, 'max_depth': 27, 'reg_lambda': 15, 'colsample_bytree': 0.9012232847273487, 'min_child_weight': 3, 'subsample': 0.7109700524017021, 'gamma': 0.6533091518495859, 'reg_alpha': 0.0029605574567047924}. Best is trial 42 with value: 0.730297340338305.
[I 2026-03-03 10:55:00,103] Trial 49 finished with value: 0.6835792330352671 and parameters: {'learning_rate': 0.0076981313251589705, 'max_depth': 28, 'reg_lambda': 36, 'colsample_bytree': 0.8702008533186625, 'min_child_weight': 2, 'subsample': 0.5856755382280114, 'gamma': 0.22503260889776233, 'reg_alpha': 0.00047454973472610076}. Best is trial 42 with value: 0.730297340338305.

In [28]:
study.best_params

{'learning_rate': 0.02212488542871817,
 'max_depth': 30,
 'reg_lambda': 5,
 'colsample_bytree': 0.915830103274166,
 'min_child_weight': 2,
 'subsample': 0.6994086343520101,
 'gamma': 0.40877113364972884,
 'reg_alpha': 0.00037891042863194194}

In [29]:
xgb_best = XGBRegressor(
        n_estimators=1000,                              
        random_state=42,
        learning_rate= 0.02212488542871817,       
        max_depth=30, 
        reg_lambda=5,
        verbosity=0,
        colsample_bytree= 0.915830103274166,
        min_child_weight=2,   
        subsample=0.6994086343520101 ,
        gamma=0.40877113364972884 ,
        reg_alpha   =0.00037891042863194194
)
%time xgb_best.fit(X_train, y_train, eval_set=[(X_valid, y_valid)])
reg_perf(xgb_best, X_train, X_valid, y_train, y_valid)

[0]	validation_0-rmse:0.86774
[1]	validation_0-rmse:0.85560
[2]	validation_0-rmse:0.84291
[3]	validation_0-rmse:0.83019
[4]	validation_0-rmse:0.81731
[5]	validation_0-rmse:0.80494
[6]	validation_0-rmse:0.79290
[7]	validation_0-rmse:0.78164
[8]	validation_0-rmse:0.77053
[9]	validation_0-rmse:0.75930
[10]	validation_0-rmse:0.74843
[11]	validation_0-rmse:0.73868
[12]	validation_0-rmse:0.72839
[13]	validation_0-rmse:0.71834
[14]	validation_0-rmse:0.70856
[15]	validation_0-rmse:0.69950
[16]	validation_0-rmse:0.69004
[17]	validation_0-rmse:0.68128
[18]	validation_0-rmse:0.67244
[19]	validation_0-rmse:0.66375
[20]	validation_0-rmse:0.65578
[21]	validation_0-rmse:0.64761
[22]	validation_0-rmse:0.63987
[23]	validation_0-rmse:0.63228
[24]	validation_0-rmse:0.62477
[25]	validation_0-rmse:0.61766
[26]	validation_0-rmse:0.61042
[27]	validation_0-rmse:0.60367
[28]	validation_0-rmse:0.59709
[29]	validation_0-rmse:0.59041
[30]	validation_0-rmse:0.58470
[31]	validation_0-rmse:0.57887
[32]	validation_0-rmse:0.57274
[33]	validation_0-rmse:0.56658
[34]	validation_0-rmse:0.56068
[35]	validation_0-rmse:0.55497
[36]	validation_0-rmse:0.54969
[37]	validation_0-rmse:0.54423
[38]	validation_0-rmse:0.53894
[39]	validation_0-rmse:0.53389
[40]	validation_0-rmse:0.52893
[41]	validation_0-rmse:0.52458
[42]	validation_0-rmse:0.52034
[43]	validation_0-rmse:0.51585
[44]	validation_0-rmse:0.51152
[45]	validation_0-rmse:0.50739
[46]	validation_0-rmse:0.50329
[47]	validation_0-rmse:0.49944
[48]	validation_0-rmse:0.49566
[49]	validation_0-rmse:0.49192
[50]	validation_0-rmse:0.48820
[51]	validation_0-rmse:0.48478
[52]	validation_0-rmse:0.48135
[53]	validation_0-rmse:0.47825
[54]	validation_0-rmse:0.47496
[55]	validation_0-rmse:0.47160
[56]	validation_0-rmse:0.46842
[57]	validation_0-rmse:0.46544
[58]	validation_0-rmse:0.46254
[59]	validation_0-rmse:0.45970
[60]	validation_0-rmse:0.45712
[61]	validation_0-rmse:0.45484
[62]	validation_0-rmse:0.45254
[63]	validation_0-rmse:0.44990
[64]	validation_0-rmse:0.44745
[65]	validation_0-rmse:0.44527
[66]	validation_0-rmse:0.44307
[67]	validation_0-rmse:0.44079
[68]	validation_0-rmse:0.43875
[69]	validation_0-rmse:0.43669
[70]	validation_0-rmse:0.43470
[71]	validation_0-rmse:0.43294
[72]	validation_0-rmse:0.43084
[73]	validation_0-rmse:0.42910
[74]	validation_0-rmse:0.42746
[75]	validation_0-rmse:0.42552
[76]	validation_0-rmse:0.42407
[77]	validation_0-rmse:0.42260
[78]	validation_0-rmse:0.42120
[79]	validation_0-rmse:0.41970
[80]	validation_0-rmse:0.41815
[81]	validation_0-rmse:0.41669
[82]	validation_0-rmse:0.41526
[83]	validation_0-rmse:0.41393
[84]	validation_0-rmse:0.41268
[85]	validation_0-rmse:0.41158
[86]	validation_0-rmse:0.41044
[87]	validation_0-rmse:0.40940
[88]	validation_0-rmse:0.40828
[89]	validation_0-rmse:0.40691
[90]	validation_0-rmse:0.40589
[91]	validation_0-rmse:0.40473
[92]	validation_0-rmse:0.40392
[93]	validation_0-rmse:0.40296
[94]	validation_0-rmse:0.40216
[95]	validation_0-rmse:0.40138
[96]	validation_0-rmse:0.40039
[97]	validation_0-rmse:0.39949
[98]	validation_0-rmse:0.39879
[99]	validation_0-rmse:0.39801
[100]	validation_0-rmse:0.39728
[101]	validation_0-rmse:0.39651
[102]	validation_0-rmse:0.39574
[103]	validation_0-rmse:0.39499
[104]	validation_0-rmse:0.39433
[105]	validation_0-rmse:0.39360
[106]	validation_0-rmse:0.39290
[107]	validation_0-rmse:0.39229
[108]	validation_0-rmse:0.39172
[109]	validation_0-rmse:0.39108
[110]	validation_0-rmse:0.39056
[111]	validation_0-rmse:0.38999
[112]	validation_0-rmse:0.38941
[113]	validation_0-rmse:0.38891
[114]	validation_0-rmse:0.38835
[115]	validation_0-rmse:0.38796
[116]	validation_0-rmse:0.38740
[117]	validation_0-rmse:0.38694
[118]	validation_0-rmse:0.38652
[119]	validation_0-rmse:0.38600
[120]	validation_0-rmse:0.38557
[121]	validation_0-rmse:0.38515
[122]	validation_0-rmse:0.38477
[123]	validation_0-rmse:0.38439
[124]	validation_0-rmse:0.38406
[125]	validation_0-rmse:0.38357
[126]	validation_0-rmse:0.38322
[127]	validation_0-rmse:0.38297
[128]	validation_0-rmse:0.38265
[129]	validation_0-rmse:0.38239
[130]	validation_0-rmse:0.38213
[131]	validation_0-rmse:0.38190
[132]	validation_0-rmse:0.38169
[133]	validation_0-rmse:0.38140
[134]	validation_0-rmse:0.38106
[135]	validation_0-rmse:0.38078
[136]	validation_0-rmse:0.38051
[137]	validation_0-rmse:0.38028
[138]	validation_0-rmse:0.38005
[139]	validation_0-rmse:0.37978
[140]	validation_0-rmse:0.37954
[141]	validation_0-rmse:0.37939
[142]	validation_0-rmse:0.37917
[143]	validation_0-rmse:0.37895
[144]	validation_0-rmse:0.37875
[145]	validation_0-rmse:0.37857
[146]	validation_0-rmse:0.37844
[147]	validation_0-rmse:0.37824
[148]	validation_0-rmse:0.37797
[149]	validation_0-rmse:0.37774
[150]	validation_0-rmse:0.37755
[151]	validation_0-rmse:0.37739
[152]	validation_0-rmse:0.37725
[153]	validation_0-rmse:0.37707
[154]	validation_0-rmse:0.37687
[155]	validation_0-rmse:0.37676
[156]	validation_0-rmse:0.37668
[157]	validation_0-rmse:0.37662
[158]	validation_0-rmse:0.37654
[159]	validation_0-rmse:0.37645
[160]	validation_0-rmse:0.37625
[161]	validation_0-rmse:0.37607
[162]	validation_0-rmse:0.37598
[163]	validation_0-rmse:0.37585
[164]	validation_0-rmse:0.37572
[165]	validation_0-rmse:0.37565
[166]	validation_0-rmse:0.37552
[167]	validation_0-rmse:0.37542
[168]	validation_0-rmse:0.37536
[169]	validation_0-rmse:0.37526
[170]	validation_0-rmse:0.37516
[171]	validation_0-rmse:0.37507
[172]	validation_0-rmse:0.37500
[173]	validation_0-rmse:0.37496
[174]	validation_0-rmse:0.37489
[175]	validation_0-rmse:0.37483
[176]	validation_0-rmse:0.37481
[177]	validation_0-rmse:0.37469
[178]	validation_0-rmse:0.37459
[179]	validation_0-rmse:0.37450
[180]	validation_0-rmse:0.37444
[181]	validation_0-rmse:0.37439
[182]	validation_0-rmse:0.37430
[183]	validation_0-rmse:0.37426
[184]	validation_0-rmse:0.37417
[185]	validation_0-rmse:0.37414
[186]	validation_0-rmse:0.37411
[187]	validation_0-rmse:0.37406
[188]	validation_0-rmse:0.37399
[189]	validation_0-rmse:0.37378
[190]	validation_0-rmse:0.37369
[191]	validation_0-rmse:0.37364
[192]	validation_0-rmse:0.37359
[193]	validation_0-rmse:0.37352
[194]	validation_0-rmse:0.37348
[195]	validation_0-rmse:0.37340
[196]	validation_0-rmse:0.37337
[197]	validation_0-rmse:0.37333
[198]	validation_0-rmse:0.37329
[199]	validation_0-rmse:0.37328
[200]	validation_0-rmse:0.37325
[201]	validation_0-rmse:0.37324
[202]	validation_0-rmse:0.37319
[203]	validation_0-rmse:0.37316
[204]	validation_0-rmse:0.37316
[205]	validation_0-rmse:0.37312
[206]	validation_0-rmse:0.37305
[207]	validation_0-rmse:0.37301
[208]	validation_0-rmse:0.37300
[209]	validation_0-rmse:0.37299
[210]	validation_0-rmse:0.37298
[211]	validation_0-rmse:0.37298
[212]	validation_0-rmse:0.37297
[213]	validation_0-rmse:0.37296
[214]	validation_0-rmse:0.37291
[215]	validation_0-rmse:0.37291
[216]	validation_0-rmse:0.37291
[217]	validation_0-rmse:0.37288
[218]	validation_0-rmse:0.37283
[219]	validation_0-rmse:0.37279
[220]	validation_0-rmse:0.37279
[221]	validation_0-rmse:0.37278
[222]	validation_0-rmse:0.37279
[223]	validation_0-rmse:0.37274
[224]	validation_0-rmse:0.37274
[225]	validation_0-rmse:0.37270
[226]	validation_0-rmse:0.37264
[227]	validation_0-rmse:0.37265
[228]	validation_0-rmse:0.37258
[229]	validation_0-rmse:0.37258
[230]	validation_0-rmse:0.37258
[231]	validation_0-rmse:0.37256
[232]	validation_0-rmse:0.37253
[233]	validation_0-rmse:0.37251
[234]	validation_0-rmse:0.37250
[235]	validation_0-rmse:0.37245
[236]	validation_0-rmse:0.37240
[237]	validation_0-rmse:0.37239
[238]	validation_0-rmse:0.37238
[239]	validation_0-rmse:0.37237
[240]	validation_0-rmse:0.37233
[241]	validation_0-rmse:0.37234
[242]	validation_0-rmse:0.37233
[243]	validation_0-rmse:0.37231
[244]	validation_0-rmse:0.37232
[245]	validation_0-rmse:0.37230
[246]	validation_0-rmse:0.37228
[247]	validation_0-rmse:0.37229
[248]	validation_0-rmse:0.37229
[249]	validation_0-rmse:0.37232
[250]	validation_0-rmse:0.37232
[251]	validation_0-rmse:0.37232
[252]	validation_0-rmse:0.37232
[253]	validation_0-rmse:0.37231
[254]	validation_0-rmse:0.37231
[255]	validation_0-rmse:0.37225
[256]	validation_0-rmse:0.37225
[257]	validation_0-rmse:0.37222
[258]	validation_0-rmse:0.37222
[259]	validation_0-rmse:0.37221
[260]	validation_0-rmse:0.37221
[261]	validation_0-rmse:0.37220
[262]	validation_0-rmse:0.37219
[263]	validation_0-rmse:0.37218
[264]	validation_0-rmse:0.37218
[265]	validation_0-rmse:0.37218
[266]	validation_0-rmse:0.37219
[267]	validation_0-rmse:0.37218
[268]	validation_0-rmse:0.37218
[269]	validation_0-rmse:0.37219
[270]	validation_0-rmse:0.37212
[271]	validation_0-rmse:0.37212
[272]	validation_0-rmse:0.37210
[273]	validation_0-rmse:0.37210
[274]	validation_0-rmse:0.37209
[275]	validation_0-rmse:0.37208
[276]	validation_0-rmse:0.37207
[277]	validation_0-rmse:0.37207
[278]	validation_0-rmse:0.37207
[279]	validation_0-rmse:0.37207
[280]	validation_0-rmse:0.37207
[281]	validation_0-rmse:0.37206
[282]	validation_0-rmse:0.37205
[283]	validation_0-rmse:0.37204
[284]	validation_0-rmse:0.37203
[285]	validation_0-rmse:0.37201
[286]	validation_0-rmse:0.37201
[287]	validation_0-rmse:0.37199
[288]	validation_0-rmse:0.37200
[289]	validation_0-rmse:0.37200
[290]	validation_0-rmse:0.37200
[291]	validation_0-rmse:0.37198
[292]	validation_0-rmse:0.37198
[293]	validation_0-rmse:0.37198
[294]	validation_0-rmse:0.37198
[295]	validation_0-rmse:0.37197
[296]	validation_0-rmse:0.37196
[297]	validation_0-rmse:0.37193
[298]	validation_0-rmse:0.37193
[299]	validation_0-rmse:0.37192
[300]	validation_0-rmse:0.37192
[301]	validation_0-rmse:0.37188
[302]	validation_0-rmse:0.37187
[303]	validation_0-rmse:0.37188
[304]	validation_0-rmse:0.37186
[305]	validation_0-rmse:0.37184
[306]	validation_0-rmse:0.37182
[307]	validation_0-rmse:0.37182
[308]	validation_0-rmse:0.37182
[309]	validation_0-rmse:0.37182
[310]	validation_0-rmse:0.37182
[311]	validation_0-rmse:0.37181
[312]	validation_0-rmse:0.37182
[313]	validation_0-rmse:0.37181
[314]	validation_0-rmse:0.37180
[315]	validation_0-rmse:0.37175
[316]	validation_0-rmse:0.37175
[317]	validation_0-rmse:0.37175
[318]	validation_0-rmse:0.37172
[319]	validation_0-rmse:0.37172
[320]	validation_0-rmse:0.37172
[321]	validation_0-rmse:0.37172
[322]	validation_0-rmse:0.37171
[323]	validation_0-rmse:0.37172
[324]	validation_0-rmse:0.37172
[325]	validation_0-rmse:0.37172
[326]	validation_0-rmse:0.37172
[327]	validation_0-rmse:0.37172
[328]	validation_0-rmse:0.37172
[329]	validation_0-rmse:0.37172
[330]	validation_0-rmse:0.37171
[331]	validation_0-rmse:0.37170
[332]	validation_0-rmse:0.37173
[333]	validation_0-rmse:0.37173
[334]	validation_0-rmse:0.37173
[335]	validation_0-rmse:0.37172
[336]	validation_0-rmse:0.37172
[337]	validation_0-rmse:0.37172
[338]	validation_0-rmse:0.37172
[339]	validation_0-rmse:0.37171
[340]	validation_0-rmse:0.37171
[341]	validation_0-rmse:0.37171
[342]	validation_0-rmse:0.37171
[343]	validation_0-rmse:0.37171
[344]	validation_0-rmse:0.37171
[345]	validation_0-rmse:0.37170
[346]	validation_0-rmse:0.37169
[347]	validation_0-rmse:0.37170
[348]	validation_0-rmse:0.37170
[349]	validation_0-rmse:0.37169
[350]	validation_0-rmse:0.37168
[351]	validation_0-rmse:0.37168
[352]	validation_0-rmse:0.37167
[353]	validation_0-rmse:0.37167
[354]	validation_0-rmse:0.37167
[355]	validation_0-rmse:0.37167
[356]	validation_0-rmse:0.37165
[357]	validation_0-rmse:0.37165
[358]	validation_0-rmse:0.37163
[359]	validation_0-rmse:0.37161
[360]	validation_0-rmse:0.37161
[361]	validation_0-rmse:0.37162
[362]	validation_0-rmse:0.37162
[363]	validation_0-rmse:0.37162
[364]	validation_0-rmse:0.37162
[365]	validation_0-rmse:0.37163
[366]	validation_0-rmse:0.37163
[367]	validation_0-rmse:0.37161
[368]	validation_0-rmse:0.37161
[369]	validation_0-rmse:0.37161
[370]	validation_0-rmse:0.37161
[371]	validation_0-rmse:0.37162
[372]	validation_0-rmse:0.37160
[373]	validation_0-rmse:0.37160
[374]	validation_0-rmse:0.37159
[375]	validation_0-rmse:0.37158
[376]	validation_0-rmse:0.37159
[377]	validation_0-rmse:0.37161
[378]	validation_0-rmse:0.37161
[379]	validation_0-rmse:0.37161
[380]	validation_0-rmse:0.37161
[381]	validation_0-rmse:0.37161
[382]	validation_0-rmse:0.37161
[383]	validation_0-rmse:0.37161
[384]	validation_0-rmse:0.37161
[385]	validation_0-rmse:0.37161
[386]	validation_0-rmse:0.37161
[387]	validation_0-rmse:0.37160
[388]	validation_0-rmse:0.37160
[389]	validation_0-rmse:0.37160
[390]	validation_0-rmse:0.37160
[391]	validation_0-rmse:0.37160
[392]	validation_0-rmse:0.37158
[393]	validation_0-rmse:0.37158
[394]	validation_0-rmse:0.37158
[395]	validation_0-rmse:0.37158
[396]	validation_0-rmse:0.37158
[397]	validation_0-rmse:0.37157
[398]	validation_0-rmse:0.37157
[399]	validation_0-rmse:0.37157
[400]	validation_0-rmse:0.37157
[401]	validation_0-rmse:0.37157
[402]	validation_0-rmse:0.37157
[403]	validation_0-rmse:0.37157
[404]	validation_0-rmse:0.37157
[405]	validation_0-rmse:0.37157
[406]	validation_0-rmse:0.37157
[407]	validation_0-rmse:0.37157
[408]	validation_0-rmse:0.37157
[409]	validation_0-rmse:0.37157
[410]	validation_0-rmse:0.37157
[411]	validation_0-rmse:0.37157
[412]	validation_0-rmse:0.37157
[413]	validation_0-rmse:0.37157
[414]	validation_0-rmse:0.37157
[415]	validation_0-rmse:0.37157
[416]	validation_0-rmse:0.37157
[417]	validation_0-rmse:0.37157
[418]	validation_0-rmse:0.37156
[419]	validation_0-rmse:0.37156
[420]	validation_0-rmse:0.37156
[421]	validation_0-rmse:0.37156
[422]	validation_0-rmse:0.37157
[423]	validation_0-rmse:0.37156
[424]	validation_0-rmse:0.37156
[425]	validation_0-rmse:0.37156
[426]	validation_0-rmse:0.37156
[427]	validation_0-rmse:0.37156
[428]	validation_0-rmse:0.37156
[429]	validation_0-rmse:0.37156
[430]	validation_0-rmse:0.37156
[431]	validation_0-rmse:0.37157
[432]	validation_0-rmse:0.37157
[433]	validation_0-rmse:0.37157
[434]	validation_0-rmse:0.37157
[435]	validation_0-rmse:0.37157
[436]	validation_0-rmse:0.37155
[437]	validation_0-rmse:0.37155
[438]	validation_0-rmse:0.37155
[439]	validation_0-rmse:0.37155
[440]	validation_0-rmse:0.37154
[441]	validation_0-rmse:0.37154
[442]	validation_0-rmse:0.37154
[443]	validation_0-rmse:0.37153
[444]	validation_0-rmse:0.37152
[445]	validation_0-rmse:0.37153
[446]	validation_0-rmse:0.37153
[447]	validation_0-rmse:0.37153
[448]	validation_0-rmse:0.37153
[449]	validation_0-rmse:0.37153
[450]	validation_0-rmse:0.37153
[451]	validation_0-rmse:0.37153
[452]	validation_0-rmse:0.37152
[453]	validation_0-rmse:0.37152
[454]	validation_0-rmse:0.37152
[455]	validation_0-rmse:0.37152
[456]	validation_0-rmse:0.37152
[457]	validation_0-rmse:0.37152
[458]	validation_0-rmse:0.37152
[459]	validation_0-rmse:0.37152
[460]	validation_0-rmse:0.37153
[461]	validation_0-rmse:0.37153
[462]	validation_0-rmse:0.37152
[463]	validation_0-rmse:0.37152
[464]	validation_0-rmse:0.37152
[465]	validation_0-rmse:0.37153
[466]	validation_0-rmse:0.37153
[467]	validation_0-rmse:0.37152
[468]	validation_0-rmse:0.37153
[469]	validation_0-rmse:0.37153
[470]	validation_0-rmse:0.37153
[471]	validation_0-rmse:0.37153
[472]	validation_0-rmse:0.37153
[473]	validation_0-rmse:0.37153
[474]	validation_0-rmse:0.37153
[475]	validation_0-rmse:0.37153
[476]	validation_0-rmse:0.37153
[477]	validation_0-rmse:0.37153
[478]	validation_0-rmse:0.37153
[479]	validation_0-rmse:0.37154
[480]	validation_0-rmse:0.37155
[481]	validation_0-rmse:0.37155
[482]	validation_0-rmse:0.37156
[483]	validation_0-rmse:0.37156
[484]	validation_0-rmse:0.37155
[485]	validation_0-rmse:0.37155
[486]	validation_0-rmse:0.37156
[487]	validation_0-rmse:0.37156
[488]	validation_0-rmse:0.37156
[489]	validation_0-rmse:0.37156
[490]	validation_0-rmse:0.37156
[491]	validation_0-rmse:0.37156
[492]	validation_0-rmse:0.37156
[493]	validation_0-rmse:0.37155
[494]	validation_0-rmse:0.37155
[495]	validation_0-rmse:0.37155
[496]	validation_0-rmse:0.37155
[497]	validation_0-rmse:0.37155
[498]	validation_0-rmse:0.37155
[499]	validation_0-rmse:0.37155
[500]	validation_0-rmse:0.37155
[501]	validation_0-rmse:0.37155
[502]	validation_0-rmse:0.37153
[503]	validation_0-rmse:0.37154
[504]	validation_0-rmse:0.37154
[505]	validation_0-rmse:0.37155
[506]	validation_0-rmse:0.37153
[507]	validation_0-rmse:0.37153
[508]	validation_0-rmse:0.37153
[509]	validation_0-rmse:0.37153
[510]	validation_0-rmse:0.37152
[511]	validation_0-rmse:0.37153
[512]	validation_0-rmse:0.37153
[513]	validation_0-rmse:0.37153
[514]	validation_0-rmse:0.37154
[515]	validation_0-rmse:0.37153
[516]	validation_0-rmse:0.37153
[517]	validation_0-rmse:0.37153
[518]	validation_0-rmse:0.37153
[519]	validation_0-rmse:0.37153
[520]	validation_0-rmse:0.37153
[521]	validation_0-rmse:0.37153
[522]	validation_0-rmse:0.37153
[523]	validation_0-rmse:0.37152
[524]	validation_0-rmse:0.37152
[525]	validation_0-rmse:0.37152
[526]	validation_0-rmse:0.37152
[527]	validation_0-rmse:0.37152
[528]	validation_0-rmse:0.37152
[529]	validation_0-rmse:0.37152
[530]	validation_0-rmse:0.37152
[531]	validation_0-rmse:0.37152
[532]	validation_0-rmse:0.37152
[533]	validation_0-rmse:0.37152
[534]	validation_0-rmse:0.37153
[535]	validation_0-rmse:0.37153
[536]	validation_0-rmse:0.37153
[537]	validation_0-rmse:0.37153
[538]	validation_0-rmse:0.37153
[539]	validation_0-rmse:0.37152
[540]	validation_0-rmse:0.37152
[541]	validation_0-rmse:0.37152
[542]	validation_0-rmse:0.37152
[543]	validation_0-rmse:0.37152
[544]	validation_0-rmse:0.37152
[545]	validation_0-rmse:0.37150
[546]	validation_0-rmse:0.37150
[547]	validation_0-rmse:0.37150
[548]	validation_0-rmse:0.37150
[549]	validation_0-rmse:0.37150
[550]	validation_0-rmse:0.37150
[551]	validation_0-rmse:0.37150
[552]	validation_0-rmse:0.37150
[553]	validation_0-rmse:0.37150
[554]	validation_0-rmse:0.37150
[555]	validation_0-rmse:0.37150
[556]	validation_0-rmse:0.37150
[557]	validation_0-rmse:0.37149
[558]	validation_0-rmse:0.37149
[559]	validation_0-rmse:0.37149
[560]	validation_0-rmse:0.37149
[561]	validation_0-rmse:0.37149
[562]	validation_0-rmse:0.37151
[563]	validation_0-rmse:0.37150
[564]	validation_0-rmse:0.37148
[565]	validation_0-rmse:0.37148
[566]	validation_0-rmse:0.37148
[567]	validation_0-rmse:0.37149
[568]	validation_0-rmse:0.37148
[569]	validation_0-rmse:0.37149
[570]	validation_0-rmse:0.37149
[571]	validation_0-rmse:0.37148
[572]	validation_0-rmse:0.37148
[573]	validation_0-rmse:0.37148
[574]	validation_0-rmse:0.37148
[575]	validation_0-rmse:0.37148
[576]	validation_0-rmse:0.37149
[577]	validation_0-rmse:0.37149
[578]	validation_0-rmse:0.37149
[579]	validation_0-rmse:0.37149
[580]	validation_0-rmse:0.37149
[581]	validation_0-rmse:0.37149
[582]	validation_0-rmse:0.37149
[583]	validation_0-rmse:0.37149
[584]	validation_0-rmse:0.37149
[585]	validation_0-rmse:0.37149
[586]	validation_0-rmse:0.37149
[587]	validation_0-rmse:0.37150
[588]	validation_0-rmse:0.37150
[589]	validation_0-rmse:0.37150
[590]	validation_0-rmse:0.37150
[591]	validation_0-rmse:0.37150
[592]	validation_0-rmse:0.37150
[593]	validation_0-rmse:0.37149
[594]	validation_0-rmse:0.37147
[595]	validation_0-rmse:0.37146
[596]	validation_0-rmse:0.37146
[597]	validation_0-rmse:0.37146
[598]	validation_0-rmse:0.37146
[599]	validation_0-rmse:0.37146
[600]	validation_0-rmse:0.37146
[601]	validation_0-rmse:0.37144
[602]	validation_0-rmse:0.37144
[603]	validation_0-rmse:0.37143
[604]	validation_0-rmse:0.37143
[605]	validation_0-rmse:0.37143
[606]	validation_0-rmse:0.37142
[607]	validation_0-rmse:0.37142
[608]	validation_0-rmse:0.37142
[609]	validation_0-rmse:0.37142
[610]	validation_0-rmse:0.37142
[611]	validation_0-rmse:0.37142
[612]	validation_0-rmse:0.37142
[613]	validation_0-rmse:0.37142
[614]	validation_0-rmse:0.37142
[615]	validation_0-rmse:0.37140
[616]	validation_0-rmse:0.37140
[617]	validation_0-rmse:0.37140
[618]	validation_0-rmse:0.37140
[619]	validation_0-rmse:0.37140
[620]	validation_0-rmse:0.37140
[621]	validation_0-rmse:0.37140
[622]	validation_0-rmse:0.37140
[623]	validation_0-rmse:0.37140
[624]	validation_0-rmse:0.37140
[625]	validation_0-rmse:0.37140
[626]	validation_0-rmse:0.37140
[627]	validation_0-rmse:0.37140

In [30]:
joblib.dump(xgb_best, '../user_data/XGBoost_Model.joblib')

['../user_data/XGBoost_Model.joblib']

---
# Submission

In [31]:
val=pd.read_csv("../data/merged_validation_data_clean.csv")

In [32]:
val["Sample Date"] = pd.to_datetime(val["Sample Date"], errors="coerce")

val["year"] = val["Sample Date"].dt.year
val["month"] = val["Sample Date"].dt.month
val["doy"] = val["Sample Date"].dt.dayofyear
val["season"] = val["month"] % 12 // 3

X_test, _ = process_df_keep_nan(val, y_fields=None, skip_flds=["Sample Date"])
X_test = X_test.reindex(columns=X_train.columns, fill_value=0)

y_pred_log = xgb_best.predict(X_test)
y_pred = np.expm1(y_pred_log)

sub = pd.read_csv("../resources/data/submission_template.csv")
sub["Total Alkalinity"] = y_pred[:,0]
sub["Electrical Conductance"] = y_pred[:,1]
sub["Dissolved Reactive Phosphorus"] = y_pred[:,2]
sub.to_csv("../user_data/submission.csv", index=False)

In [33]:
pred = xgb_best.predict(X_test)
print(pred.shape)

(200, 3)

In [34]:
print("log pred example:", y_pred_log[0])
print("real pred example:", np.expm1(y_pred_log[0]))

log pred example: [2.776441  5.400292  3.0970461]
real pred example: [ 15.061756 220.47105   21.132479]

In [36]:
import pandas as pd
ls = pd.read_csv("../data/processed/landsat_api_validation.csv")
print(ls["Index"].min(), ls["Index"].max(), ls["Index"].nunique())

0 199 200

In [37]:
val = pd.read_csv("../data/merged_validation_data_clean.csv")
print(val[["blue","green","red","nir08","swir16","swir22","pet","ppt","tmax","tmin","q"]].describe().T)

        count          mean          std      min           25%          50%  \
blue    172.0   9027.183140  2408.712104  7770.00   8208.125000   8639.25000
green   196.0   9955.094388  2285.693956  8210.50   9020.625000   9622.50000
red     172.0  10203.186047  2544.293075  8065.50   9003.000000   9773.25000
nir08   196.0  14937.841837  2828.830922  8823.50  13416.125000  14684.00000
swir16  196.0  12562.920918  1928.079536  8307.00  11334.000000  12425.75000
swir22  196.0  10419.066327  1547.392099  8107.50   9221.000000  10122.25000
pet     200.0    160.278003    25.346462    60.50    140.750000    158.40001
ppt     200.0     50.091500    40.372768     1.20     18.850000     38.55000
tmax    200.0     24.422150     3.350726    15.48     22.289999     24.34000
tmin    200.0     11.699300     3.956054    -0.85      9.300000     12.00500
q       200.0      3.098500     5.743893     0.10      0.975000      1.95000

              75%       max
blue     9206.750  30990.00
green   10250.500  32467.50
red     10916.250  32938.50
nir08   16371.375  33948.00
swir16  13576.125  18537.50
swir22  11296.375  16123.00
pet       173.700    218.20
ppt        66.400    183.00
tmax       26.435     33.98
tmin       14.480     18.90
q           3.325     64.00